### ISSUE TITLE
404

### ISSUE THREAD

**Issue by DexterInd** [funstoreHQ/funstore#2]
I ran the script, and it automatically rebooted. 

Typing http://funstore.local , it redirects to 
http://funstore.local/dashboard/
And gives:

Not Found

The requested URL /dashboard/ was not found on this server.

Apache/2.2.22 (Debian) Server at funstore.local Port 80

**Comment by funstoreIO** [comment]
The new and updated repo is at https://github.com/funstoreIO/funstoreSetup.

**Comment by DexterInd** [comment]
Nice, thanks!  We'll try it out today!
